-- Generated by scripts/split-househelp-sql.mjs — không sửa tay; chạy lại script sau khi đổi househelp.sql
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = "+00:00";
SET FOREIGN_KEY_CHECKS=0;

-- Drop existing tables
DROP TABLE IF EXISTS system_logs;
DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS coupon_usage;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS chat_read_status;
DROP TABLE IF EXISTS verification_documents;
DROP TABLE IF EXISTS verification_requests;
DROP TABLE IF EXISTS file_uploads;
DROP TABLE IF EXISTS recurring_bookings;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS reviews;

DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS housekeeper_services;
DROP TABLE IF EXISTS housekeepers;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS users;

-- ========================
-- users
-- ========================
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255),
  phone VARCHAR(20),
  role ENUM('customer','housekeeper','admin') DEFAULT 'customer',
  idCardFront LONGTEXT,
  idCardBack LONGTEXT,
  avatar VARCHAR(255),
  dateOfBirth DATE,
  gender ENUM('male','female','other'),
  address TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  city VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  district VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  bio TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  languages VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  emergencyContact VARCHAR(20),
  emergencyContactName VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  isVerified BOOLEAN DEFAULT FALSE,
  isApproved BOOLEAN DEFAULT FALSE,
  verifiedAt DATETIME,
  lastActiveAt DATETIME,
  -- Google OAuth fields
  googleId VARCHAR(255) UNIQUE,
  authProvider ENUM('local','google') DEFAULT 'local',
  profilePicture VARCHAR(500),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- housekeepers
-- ========================
CREATE TABLE housekeepers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  rating FLOAT DEFAULT 0,
  totalReviews INT DEFAULT 0,
  services VARCHAR(500),
  price DECIMAL(10,2),
  priceType ENUM('hourly','daily','per_service') DEFAULT 'hourly',
  available BOOLEAN DEFAULT TRUE,
  description TEXT,
  experience INT DEFAULT 0,
  skills JSON,
  certifications JSON,
  workingDays JSON,
  workingHours VARCHAR(50),
  serviceRadius INT DEFAULT 10,
  profileImages JSON,
  hasInsurance BOOLEAN DEFAULT FALSE,
  insuranceInfo TEXT,
  specialOffers JSON,
  completedJobs INT DEFAULT 0,
  responseTime INT DEFAULT 60,
  cancellationRate FLOAT DEFAULT 0,
  isTopRated BOOLEAN DEFAULT FALSE,
  badges JSON,
  lastOnline DATETIME,
  -- Quick Booking related fields
  backgroundChecked BOOLEAN DEFAULT FALSE,
  insured BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- services
-- ========================
CREATE TABLE services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci UNIQUE,
  description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  icon VARCHAR(100),
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- housekeeper_services
-- ========================
CREATE TABLE housekeeper_services (
  housekeeperId INT,
  serviceId INT,
  priceOverride DECIMAL(10,2),
  PRIMARY KEY (housekeeperId, serviceId),
  FOREIGN KEY (housekeeperId) REFERENCES housekeepers(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE CASCADE
);

-- ========================
-- bookings (giữ nguyên startDate, endDate, totalPrice)
-- ========================
CREATE TABLE bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT NOT NULL,
  housekeeperId INT NOT NULL,
  serviceId INT,
  startDate DATETIME NOT NULL,
  endDate DATETIME,
  status ENUM('pending','confirmed','in_progress','completed','cancelled','rejected') DEFAULT 'pending',
  paymentStatus ENUM('pending','success','failed') DEFAULT 'pending',
  totalPrice DECIMAL(10,2),
  notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  customerAddress TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  -- Cột bổ sung cho tiện ích
  time VARCHAR(10),
  duration INT DEFAULT 2,
  location TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  customerName VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  customerEmail VARCHAR(255),
  customerPhone VARCHAR(20),
  housekeeperName VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  service VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  completionProofUrl VARCHAR(500),
  completionNotes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  completionRequestedAt DATETIME,
  customerConfirmedAt DATETIME,
  -- Quick Booking columns
  urgency ENUM('normal', 'urgent', 'asap') DEFAULT 'normal',
  isQuickBooking BOOLEAN DEFAULT FALSE,
  matchScore INT DEFAULT 0,
  FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (housekeeperId) REFERENCES housekeepers(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES services(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- reviews
-- ========================
CREATE TABLE reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT,
  housekeeperId INT NOT NULL,
  customerId INT NOT NULL,
  rating INT CHECK (rating BETWEEN 1 AND 5),
  comment TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  isVisible BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE SET NULL,
  FOREIGN KEY (housekeeperId) REFERENCES housekeepers(id) ON DELETE CASCADE,
  FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- notifications
-- ========================
CREATE TABLE notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  type VARCHAR(50) NOT NULL,
  urgency ENUM('normal', 'urgent', 'asap') DEFAULT 'normal',
  title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  message TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  bookingId INT NULL,
  data JSON NULL,
  read_status TINYINT(1) DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_userId (userId),
  INDEX idx_createdAt (createdAt),
  INDEX idx_read_status (read_status),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- reports (báo cáo vi phạm)
-- ========================
CREATE TABLE reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  customerId INT NOT NULL,
  housekeeperId INT NOT NULL,
  reportType ENUM('late_arrival','no_show','inappropriate_behavior','poor_service','damage','other') NOT NULL,
  title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  evidence TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, -- URLs của ảnh/video bằng chứng
  status ENUM('pending','investigating','resolved','dismissed') DEFAULT 'pending',
  adminResponse TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  severity ENUM('low','medium','high','critical') DEFAULT 'medium',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  resolvedAt DATETIME NULL,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE CASCADE,
  FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (housekeeperId) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_status (status),
  INDEX idx_reportType (reportType),
  INDEX idx_severity (severity),
  INDEX idx_createdAt (createdAt)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- warnings (cảnh cáo housekeeper)
-- ========================
CREATE TABLE warnings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  housekeeperId INT NOT NULL,
  reportId INT NOT NULL,
  adminId INT NOT NULL,
  warningType ENUM('verbal','written','final','suspension') DEFAULT 'written',
  title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  message TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  severity ENUM('low','medium','high','critical') DEFAULT 'medium',
  isRead BOOLEAN DEFAULT FALSE,
  expiresAt DATETIME NULL, -- Cho suspension warnings
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  readAt DATETIME NULL,
  FOREIGN KEY (housekeeperId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reportId) REFERENCES reports(id) ON DELETE CASCADE,
  FOREIGN KEY (adminId) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_housekeeperId (housekeeperId),
  INDEX idx_createdAt (createdAt),
  INDEX idx_warningType (warningType),
  INDEX idx_isRead (isRead)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- payments (mới)
-- ========================
CREATE TABLE payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  customerId INT NOT NULL,
  method ENUM('cash','momo','credit_card','bank_transfer','e_wallet') NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  platformFee DECIMAL(10,2) DEFAULT 0,
  housekeeperAmount DECIMAL(10,2) DEFAULT 0,
  settlementStatus ENUM('pending','holding','ready','paid','cash_collected','cancelled') DEFAULT 'pending',
  platformAccount VARCHAR(100),
  settledAt DATETIME,
  payoutReference VARCHAR(100),
  status ENUM('pending','success','failed','refunded') DEFAULT 'pending',
  transactionCode VARCHAR(100),
  paidAt DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE CASCADE,
  FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE
);

-- ========================
-- chat_messages (mới)
-- ========================
CREATE TABLE chat_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  senderId INT NOT NULL,
  receiverId INT NOT NULL,
  message TEXT,
  messageType ENUM('text','image','file') DEFAULT 'text',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE CASCADE,
  FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (receiverId) REFERENCES users(id) ON DELETE CASCADE
);

-- ========================
-- recurring_bookings (mới)
-- ========================
CREATE TABLE recurring_bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT NOT NULL,
  housekeeperId INT,
  serviceId INT,
  frequency ENUM('daily','weekly','monthly') NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE,
  nextBookingDate DATE,
  status ENUM('active','paused','cancelled') DEFAULT 'active',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (housekeeperId) REFERENCES housekeepers(id) ON DELETE SET NULL,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE SET NULL
);

-- ========================
-- system_logs (mới)
-- ========================
CREATE TABLE system_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT,
  action VARCHAR(100),
  description TEXT,
  ipAddress VARCHAR(50),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

-- ========================
-- file_uploads (mới)
-- ========================
CREATE TABLE file_uploads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  fileName VARCHAR(255) NOT NULL,
  originalName VARCHAR(255) NOT NULL,
  filePath VARCHAR(500) NOT NULL,
  fileType ENUM('avatar','id_card_front','id_card_back','profile_image','document') NOT NULL,
  mimeType VARCHAR(100),
  fileSize INT,
  uploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_userId_fileType (userId, fileType)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Bảng trạng thái đọc tin nhắn
CREATE TABLE `chat_read_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userId` int(11) NOT NULL,
  `bookingId` int(11) NOT NULL,
  `lastReadAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_booking` (`userId`, `bookingId`),
  KEY `idx_userId` (`userId`),
  KEY `idx_bookingId` (`bookingId`),
  CONSTRAINT `fk_chat_read_user` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chat_read_booking` FOREIGN KEY (`bookingId`) REFERENCES `bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- VERIFICATION DOCUMENTS TABLE
-- ========================
CREATE TABLE verification_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  requestId INT NULL,
  documentType ENUM('id_card_front','id_card_back','selfie','certificate','license','insurance','other') NOT NULL,
  filePath VARCHAR(500) NOT NULL,
  originalName VARCHAR(255) NOT NULL,
  status ENUM('pending','approved','rejected') DEFAULT 'pending',
  adminNotes TEXT,
  reviewedBy INT NULL,
  reviewedAt DATETIME NULL,
  uploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewedBy) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_request_status (requestId, status),
  INDEX idx_user_status (userId, status),
  INDEX idx_status_type (status, documentType)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- VERIFICATION REQUESTS TABLE  
-- ========================
CREATE TABLE verification_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  requestType ENUM('initial_verification','document_update','resubmission') DEFAULT 'initial_verification',
  status ENUM('pending','under_review','approved','rejected','requires_more_info') DEFAULT 'pending',
  submittedDocuments JSON,
  aiStatus ENUM('not_configured','pending','passed','failed','needs_review','error') DEFAULT 'pending',
  aiProvider VARCHAR(50),
  aiScore DECIMAL(8,2),
  aiOcrName VARCHAR(255),
  aiOcrIdNumber VARCHAR(64),
  aiOcrDob VARCHAR(64),
  aiOcrAddress TEXT,
  aiOcrFront JSON,
  aiOcrBack JSON,
  aiFaceMatch JSON,
  aiRawResult JSON,
  aiCheckedAt DATETIME NULL,
  adminNotes TEXT,
  userNotes TEXT,
  priority ENUM('low','normal','high','urgent') DEFAULT 'normal',
  assignedTo INT NULL,
  submittedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  reviewedAt DATETIME NULL,
  completedAt DATETIME NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (assignedTo) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_status_priority (status, priority),
  INDEX idx_assigned_status (assignedTo, status)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ========================
-- ADDITIONAL INDEXES FOR PERFORMANCE
-- ========================
CREATE INDEX idx_users_email_auth ON users(email, authProvider);
CREATE INDEX idx_users_google_id ON users(googleId);
CREATE INDEX idx_users_verification_status ON users(isVerified, isApproved, role);
CREATE INDEX idx_file_uploads_user_type ON file_uploads(userId, fileType);

-- Quick Booking indexes
CREATE INDEX idx_bookings_quick ON bookings(isQuickBooking, urgency, createdAt);
CREATE INDEX idx_housekeepers_matching ON housekeepers(price, available, backgroundChecked, insured);
CREATE INDEX idx_housekeeper_services_lookup ON housekeeper_services(housekeeperId, serviceId);
CREATE INDEX idx_notifications_urgency ON notifications(urgency, type, createdAt);


CREATE TABLE coupons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  description VARCHAR(255) NOT NULL,
  discount DECIMAL(10,2) NOT NULL,
  type ENUM('percentage', 'fixed') NOT NULL,
  minAmount DECIMAL(10,2) DEFAULT 0,
  maxDiscount DECIMAL(10,2) DEFAULT 0,
  firstTimeOnly BOOLEAN DEFAULT FALSE,
  isActive BOOLEAN DEFAULT TRUE,
  usageLimit INT DEFAULT NULL,
  usedCount INT DEFAULT 0,
  expiresAt DATETIME DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE coupon_usage (
  id INT AUTO_INCREMENT PRIMARY KEY,
  couponId INT NOT NULL,
  userId INT NOT NULL,
  bookingId INT NULL,
  discountAmount DECIMAL(10,2) NOT NULL,
  usedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (couponId) REFERENCES coupons(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE SET NULL,
  INDEX idx_coupon_user (couponId, userId),
  INDEX idx_user_coupon (userId, couponId)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
